name: ArchiveRepository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run:  zip -r LaravelPackge.zip
    - name: Run a multi-line script
      run: echo "Finish"
